<?php

namespace Database\Seeders;

use App\Models\Isletme;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class IsletmeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universiteler = [
            ['baslik' => 'Abant İzzet Baysal Üniversitesi',       'il' => 14, 'mailUzanti' => 'ibu.edu.tr'],
            ['baslik' => 'Abdullah Gül Üniversitesi',              'il' => 38, 'mailUzanti' => 'agu.edu.tr'],
            ['baslik' => 'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi', 'il' => 1,  'mailUzanti' => 'adanabtu.edu.tr'],
            ['baslik' => 'Adıyaman Üniversitesi',                  'il' => 2,  'mailUzanti' => 'adiyaman.edu.tr'],
            ['baslik' => 'Afyon Kocatepe Üniversitesi',            'il' => 3,  'mailUzanti' => 'aku.edu.tr'],
            ['baslik' => 'Afyonkarahisar Sağlık Bilimleri Üniversitesi', 'il' => 3, 'mailUzanti' => 'afsu.edu.tr'],
            ['baslik' => 'Ağrı İbrahim Çeçen Üniversitesi',        'il' => 4,  'mailUzanti' => 'agri.edu.tr'],
            ['baslik' => 'Aksaray Üniversitesi',                   'il' => 68, 'mailUzanti' => 'aksaray.edu.tr'],
            ['baslik' => 'Amasya Üniversitesi',                    'il' => 5,  'mailUzanti' => 'amasya.edu.tr'],
            ['baslik' => 'Ankara Hacı Bayram Veli Üniversitesi',   'il' => 6,  'mailUzanti' => 'hacibayram.edu.tr'],
            ['baslik' => 'Ankara Müzik ve Güzel Sanatlar Üniversitesi', 'il' => 6, 'mailUzanti' => 'mgu.edu.tr'],
            ['baslik' => 'Ankara Sosyal Bilimler Üniversitesi',     'il' => 6,  'mailUzanti' => 'asbu.edu.tr'],
            ['baslik' => 'Ankara Üniversitesi',                     'il' => 6,  'mailUzanti' => 'ankara.edu.tr'],
            ['baslik' => 'Antalya Akev Üniversitesi (Vakıf)',       'il' => 7,  'mailUzanti' => 'antalyaakev.edu.tr'],
            ['baslik' => 'Antalya Bilim Üniversitesi (Vakıf)',      'il' => 7,  'mailUzanti' => 'antalya.edu.tr'],
            ['baslik' => 'Ardahan Üniversitesi',                    'il' => 75, 'mailUzanti' => 'ardahan.edu.tr'],
            ['baslik' => 'Artvin Çoruh Üniversitesi',               'il' => 8,  'mailUzanti' => 'artvin.edu.tr'],
            ['baslik' => 'Atatürk Üniversitesi',                    'il' => 25, 'mailUzanti' => 'atauni.edu.tr'],
            ['baslik' => 'Bahçeşehir Üniversitesi (Vakıf)',         'il' => 34, 'mailUzanti' => 'bahcesehir.edu.tr'],
            ['baslik' => 'Balıkesir Üniversitesi',                  'il' => 10, 'mailUzanti' => 'balikesir.edu.tr'],
            ['baslik' => 'Bandırma Onyedi Eylül Üniversitesi',      'il' => 10, 'mailUzanti' => 'bandirma.edu.tr'],
            ['baslik' => 'Bartın Üniversitesi',                     'il' => 74, 'mailUzanti' => 'bartin.edu.tr'],
            ['baslik' => 'Batman Üniversitesi',                     'il' => 72, 'mailUzanti' => 'batman.edu.tr'],
            ['baslik' => 'Bayburt Üniversitesi',                    'il' => 69, 'mailUzanti' => 'bayburt.edu.tr'],
            ['baslik' => 'Beykent Üniversitesi (Vakıf)',            'il' => 34, 'mailUzanti' => 'beykent.edu.tr'],
            ['baslik' => 'Bezmialem Vakıf Üniversitesi (Vakıf)',    'il' => 34, 'mailUzanti' => 'bezmialem.edu.tr'],
            ['baslik' => 'Bilecik Şeyh Edebali Üniversitesi',       'il' => 11, 'mailUzanti' => 'bilecik.edu.tr'],
            ['baslik' => 'Bingöl Üniversitesi',                     'il' => 12, 'mailUzanti' => 'bingol.edu.tr'],
            ['baslik' => 'Bitlis Eren Üniversitesi',                'il' => 13, 'mailUzanti' => 'bitliseren.edu.tr'],
            ['baslik' => 'Boğaziçi Üniversitesi',                   'il' => 34, 'mailUzanti' => 'boun.edu.tr'],
            ['baslik' => 'Bolu Abant İzzet Baysal Üniversitesi',    'il' => 14, 'mailUzanti' => 'ibu.edu.tr'],
            ['baslik' => 'Bursa Teknik Üniversitesi',               'il' => 16, 'mailUzanti' => 'btu.edu.tr'],
            ['baslik' => 'Bursa Uludağ Üniversitesi',               'il' => 16, 'mailUzanti' => 'uludag.edu.tr'],
            ['baslik' => 'Çanakkale Onsekiz Mart Üniversitesi',     'il' => 17, 'mailUzanti' => 'comu.edu.tr'],
            ['baslik' => 'Çankırı Karatekin Üniversitesi',          'il' => 18, 'mailUzanti' => 'karatekin.edu.tr'],
            ['baslik' => 'Çukurova Üniversitesi',                   'il' => 1,  'mailUzanti' => 'cu.edu.tr'],
            ['baslik' => 'Demiroğlu Bilim Üniversitesi (Vakıf)',    'il' => 34, 'mailUzanti' => 'bilim.edu.tr'],
            ['baslik' => 'Dicle Üniversitesi',                     'il' => 21, 'mailUzanti' => 'dicle.edu.tr'],
            ['baslik' => 'Dokuz Eylül Üniversitesi',                'il' => 35, 'mailUzanti' => 'deu.edu.tr'],
            ['baslik' => 'Düzce Üniversitesi',                      'il' => 81, 'mailUzanti' => 'duzce.edu.tr'],
            ['baslik' => 'Ege Üniversitesi',                        'il' => 35, 'mailUzanti' => 'ege.edu.tr'],
            ['baslik' => 'Erciyes Üniversitesi',                    'il' => 38, 'mailUzanti' => 'erciyes.edu.tr'],
            ['baslik' => 'Erzincan Binali Yıldırım Üniversitesi',   'il' => 24, 'mailUzanti' => 'ebyu.edu.tr'],
            ['baslik' => 'Erzurum Teknik Üniversitesi',             'il' => 25, 'mailUzanti' => 'erzurum.edu.tr'],
            ['baslik' => 'Eskişehir Osmangazi Üniversitesi',        'il' => 26, 'mailUzanti' => 'ogu.edu.tr'],
            ['baslik' => 'Eskişehir Teknik Üniversitesi',           'il' => 26, 'mailUzanti' => 'eskisehir.edu.tr'],
            ['baslik' => 'Fırat Üniversitesi',                      'il' => 23, 'mailUzanti' => 'firat.edu.tr'],
            ['baslik' => 'Galatasaray Üniversitesi',                'il' => 34, 'mailUzanti' => 'gsu.edu.tr'],
            ['baslik' => 'Gaziantep İslam Bilim ve Teknoloji Üniversitesi', 'il' => 27, 'mailUzanti' => 'gibtu.edu.tr'],
            ['baslik' => 'Gaziantep Üniversitesi',                  'il' => 27, 'mailUzanti' => 'gantep.edu.tr'],
            ['baslik' => 'Gaziosmanpaşa Üniversitesi (Tokat Gaziosmanpaşa)', 'il' => 60, 'mailUzanti' => 'gop.edu.tr'],
            ['baslik' => 'Gebze Teknik Üniversitesi',               'il' => 41, 'mailUzanti' => 'gtu.edu.tr'],
            ['baslik' => 'Giresun Üniversitesi',                    'il' => 28, 'mailUzanti' => 'giresun.edu.tr'],
            ['baslik' => 'Gümüşhane Üniversitesi',                  'il' => 29, 'mailUzanti' => 'gumushane.edu.tr'],
            ['baslik' => 'Hacettepe Üniversitesi',                  'il' => 6,  'mailUzanti' => 'hacettepe.edu.tr'],
            ['baslik' => 'Hakkari Üniversitesi',                    'il' => 30, 'mailUzanti' => 'hakkari.edu.tr'],
            ['baslik' => 'Hatay Mustafa Kemal Üniversitesi',        'il' => 31, 'mailUzanti' => 'mku.edu.tr'],
            ['baslik' => 'Harran Üniversitesi',                     'il' => 63, 'mailUzanti' => 'harran.edu.tr'],
            ['baslik' => 'Hitit Üniversitesi',                      'il' => 19, 'mailUzanti' => 'hitit.edu.tr'],
            ['baslik' => 'Iğdır Üniversitesi',                      'il' => 76, 'mailUzanti' => 'igdir.edu.tr'],
            ['baslik' => 'İbn Haldun Üniversitesi (Vakıf)',         'il' => 34, 'mailUzanti' => 'ihu.edu.tr'],
            ['baslik' => 'İhsan Doğramacı Bilkent Üniversitesi (Vakıf)', 'il' => 6, 'mailUzanti' => 'bilkent.edu.tr'],
            ['baslik' => 'İnönü Üniversitesi',                      'il' => 44, 'mailUzanti' => 'inonu.edu.tr'],
            ['baslik' => 'İskenderun Teknik Üniversitesi',          'il' => 31, 'mailUzanti' => 'iste.edu.tr'],
            ['baslik' => 'İstanbul 29 Mayıs Üniversitesi (Vakıf)',  'il' => 34, 'mailUzanti' => '29mayis.edu.tr'],
            ['baslik' => 'İstanbul Arel Üniversitesi (Vakıf)',      'il' => 34, 'mailUzanti' => 'arel.edu.tr'],
            ['baslik' => 'İstanbul Atlas Üniversitesi (Vakıf)',     'il' => 34, 'mailUzanti' => 'atlas.edu.tr'],
            ['baslik' => 'İstanbul Aydın Üniversitesi (Vakıf)',     'il' => 34, 'mailUzanti' => 'aydin.edu.tr'],
            ['baslik' => 'İstanbul Beykent Üniversitesi (Vakıf)',   'il' => 34, 'mailUzanti' => 'beykent.edu.tr'],
            ['baslik' => 'İstanbul Bilgi Üniversitesi (Vakıf)',     'il' => 34, 'mailUzanti' => 'bilgi.edu.tr'],
            ['baslik' => 'İstanbul Esenyurt Üniversitesi (Vakıf)',  'il' => 34, 'mailUzanti' => 'esenyurt.edu.tr'],
            ['baslik' => 'İstanbul Galata Üniversitesi (Vakıf)',    'il' => 34, 'mailUzanti' => 'galata.edu.tr'],
            ['baslik' => 'İstanbul Gedik Üniversitesi (Vakıf)',     'il' => 34, 'mailUzanti' => 'gedik.edu.tr'],
            ['baslik' => 'İstanbul Gelişim Üniversitesi (Vakıf)',   'il' => 34, 'mailUzanti' => 'gelisim.edu.tr'],
            ['baslik' => 'İstanbul Kent Üniversitesi (Vakıf)',      'il' => 34, 'mailUzanti' => 'kent.edu.tr'],
            ['baslik' => 'İstanbul Kültür Üniversitesi (Vakıf)',    'il' => 34, 'mailUzanti' => 'iku.edu.tr'],
            ['baslik' => 'İstanbul Medeniyet Üniversitesi',         'il' => 34, 'mailUzanti' => 'medeniyet.edu.tr'],
            ['baslik' => 'İstanbul Medipol Üniversitesi (Vakıf)',   'il' => 34, 'mailUzanti' => 'medipol.edu.tr'],
            ['baslik' => 'İstanbul Okan Üniversitesi (Vakıf)',      'il' => 34, 'mailUzanti' => 'okan.edu.tr'],
            ['baslik' => 'İstanbul Rumeli Üniversitesi (Vakıf)',    'il' => 34, 'mailUzanti' => 'rumeli.edu.tr'],
            ['baslik' => 'İstanbul Sabahattin Zaim Üniversitesi (Vakıf)', 'il' => 34, 'mailUzanti' => 'izu.edu.tr'],
            ['baslik' => 'İstanbul Teknik Üniversitesi',            'il' => 34, 'mailUzanti' => 'itu.edu.tr'],
            ['baslik' => 'İstanbul Ticaret Üniversitesi (Vakıf)',   'il' => 34, 'mailUzanti' => 'iticu.edu.tr'],
            ['baslik' => 'İstanbul Üniversitesi',                   'il' => 34, 'mailUzanti' => 'istanbul.edu.tr'],
            ['baslik' => 'İstanbul Yeni Yüzyıl Üniversitesi (Vakıf)', 'il' => 34, 'mailUzanti' => 'yeniyuzyil.edu.tr'],
            ['baslik' => 'İstinye Üniversitesi (Vakıf)',            'il' => 34, 'mailUzanti' => 'istinye.edu.tr'],
            ['baslik' => 'İzmir Bakırçay Üniversitesi',             'il' => 35, 'mailUzanti' => 'bakircay.edu.tr'],
            ['baslik' => 'İzmir Demokrasi Üniversitesi',            'il' => 35, 'mailUzanti' => 'idu.edu.tr'],
            ['baslik' => 'İzmir Ekonomi Üniversitesi (Vakıf)',      'il' => 35, 'mailUzanti' => 'ieu.edu.tr'],
            ['baslik' => 'İzmir Katip Çelebi Üniversitesi',         'il' => 35, 'mailUzanti' => 'ikcu.edu.tr'],
            ['baslik' => 'İzmir Tınaztepe Üniversitesi (Vakıf)',    'il' => 35, 'mailUzanti' => 'tinaztepe.edu.tr'],
            ['baslik' => 'İzmir Yüksek Teknoloji Enstitüsü',        'il' => 35, 'mailUzanti' => 'iyte.edu.tr'],
            ['baslik' => 'Kadir Has Üniversitesi (Vakıf)',          'il' => 34, 'mailUzanti' => 'khas.edu.tr'],
            ['baslik' => 'Kafkas Üniversitesi',                     'il' => 36, 'mailUzanti' => 'kafkas.edu.tr'],
            ['baslik' => 'Kahramanmaraş İstiklal Üniversitesi',     'il' => 46, 'mailUzanti' => 'istiklal.edu.tr'],
            ['baslik' => 'Kahramanmaraş Sütçü İmam Üniversitesi',   'il' => 46, 'mailUzanti' => 'ksu.edu.tr'],
            ['baslik' => 'Kapadokya Üniversitesi (Vakıf)',          'il' => 50, 'mailUzanti' => 'kapadokya.edu.tr'],
            ['baslik' => 'Karabük Üniversitesi',                    'il' => 78, 'mailUzanti' => 'karabuk.edu.tr'],
            ['baslik' => 'Karadeniz Teknik Üniversitesi',           'il' => 61, 'mailUzanti' => 'ktu.edu.tr'],
            ['baslik' => 'Karamanoğlu Mehmetbey Üniversitesi',      'il' => 70, 'mailUzanti' => 'kmu.edu.tr'],
            ['baslik' => 'Kastamonu Üniversitesi',                  'il' => 37, 'mailUzanti' => 'kastamonu.edu.tr'],
            ['baslik' => 'Kayseri Üniversitesi',                    'il' => 38, 'mailUzanti' => 'kayseri.edu.tr'],
            ['baslik' => 'Kırıkkale Üniversitesi',                  'il' => 71, 'mailUzanti' => 'kku.edu.tr'],
            ['baslik' => 'Kırklareli Üniversitesi',                 'il' => 39, 'mailUzanti' => 'klu.edu.tr'],
            ['baslik' => 'Kilis 7 Aralık Üniversitesi',             'il' => 79, 'mailUzanti' => 'kilis.edu.tr'],
            ['baslik' => 'Kocaeli Üniversitesi',                    'il' => 41, 'mailUzanti' => 'kocaeli.edu.tr'],
            ['baslik' => 'Konya Gıda ve Tarım Üniversitesi (Vakıf)', 'il' => 42, 'mailUzanti' => 'gidatarim.edu.tr'],
            ['baslik' => 'Konya Teknik Üniversitesi',               'il' => 42, 'mailUzanti' => 'ktun.edu.tr'],
            ['baslik' => 'Kütahya Dumlupınar Üniversitesi',         'il' => 43, 'mailUzanti' => 'dpu.edu.tr'],
            ['baslik' => 'Kütahya Sağlık Bilimleri Üniversitesi',   'il' => 43, 'mailUzanti' => 'ksbu.edu.tr'],
            ['baslik' => 'Malatya Turgut Özal Üniversitesi',        'il' => 44, 'mailUzanti' => 'mtu.edu.tr'],
            ['baslik' => 'Manisa Celal Bayar Üniversitesi',         'il' => 45, 'mailUzanti' => 'cbu.edu.tr'],
            ['baslik' => 'Mardin Artuklu Üniversitesi',             'il' => 47, 'mailUzanti' => 'artuklu.edu.tr'],
            ['baslik' => 'Marmara Üniversitesi',                    'il' => 34, 'mailUzanti' => 'marmara.edu.tr'],
            ['baslik' => 'Mersin Üniversitesi',                     'il' => 33, 'mailUzanti' => 'mersin.edu.tr'],
            ['baslik' => 'Mimar Sinan Güzel Sanatlar Üniversitesi', 'il' => 34, 'mailUzanti' => 'msgsu.edu.tr'],
            ['baslik' => 'Muğla Sıtkı Koçman Üniversitesi',         'il' => 48, 'mailUzanti' => 'mu.edu.tr'],
            ['baslik' => 'Munzur Üniversitesi',                     'il' => 62, 'mailUzanti' => 'munzur.edu.tr'],
            ['baslik' => 'Mustafa Kemal Üniversitesi (Hatay Mustafa Kemal)', 'il' => 31, 'mailUzanti' => 'mku.edu.tr'],
            ['baslik' => 'Muş Alparslan Üniversitesi',              'il' => 49, 'mailUzanti' => 'alparslan.edu.tr'],
            ['baslik' => 'Nevşehir Hacı Bektaş Veli Üniversitesi',  'il' => 50, 'mailUzanti' => 'nevsehir.edu.tr'],
            ['baslik' => 'Niğde Ömer Halisdemir Üniversitesi',      'il' => 51, 'mailUzanti' => 'ohu.edu.tr'],
            ['baslik' => 'Nuh Naci Yazgan Üniversitesi (Vakıf)',    'il' => 38, 'mailUzanti' => 'nny.edu.tr'],
            ['baslik' => 'Ondokuz Mayıs Üniversitesi',             'il' => 55, 'mailUzanti' => 'omu.edu.tr'],
            ['baslik' => 'Ordu Üniversitesi',                       'il' => 52, 'mailUzanti' => 'odu.edu.tr'],
            ['baslik' => 'Orta Doğu Teknik Üniversitesi',           'il' => 6,  'mailUzanti' => 'metu.edu.tr'],
            ['baslik' => 'Osmaniye Korkut Ata Üniversitesi',        'il' => 80, 'mailUzanti' => 'osmaniye.edu.tr'],
            ['baslik' => 'Ostim Teknik Üniversitesi (Vakıf)',       'il' => 6,  'mailUzanti' => 'ostimteknik.edu.tr'],
            ['baslik' => 'Pamukkale Üniversitesi',                  'il' => 20, 'mailUzanti' => 'pau.edu.tr'],
            ['baslik' => 'Recep Tayyip Erdoğan Üniversitesi',       'il' => 53, 'mailUzanti' => 'erdogan.edu.tr'],
            ['baslik' => 'Sağlık Bilimleri Üniversitesi',           'il' => 34, 'mailUzanti' => 'sbu.edu.tr'],
            ['baslik' => 'Sakarya Uygulamalı Bilimler Üniversitesi', 'il' => 54, 'mailUzanti' => 'subu.edu.tr'],
            ['baslik' => 'Sakarya Üniversitesi',                    'il' => 54, 'mailUzanti' => 'sakarya.edu.tr'],
            ['baslik' => 'Samsun Üniversitesi',                     'il' => 55, 'mailUzanti' => 'samsun.edu.tr'],
            ['baslik' => 'Selçuk Üniversitesi',                     'il' => 42, 'mailUzanti' => 'selcuk.edu.tr'],
            ['baslik' => 'Siirt Üniversitesi',                      'il' => 56, 'mailUzanti' => 'siirt.edu.tr'],
            ['baslik' => 'Sinop Üniversitesi',                      'il' => 57, 'mailUzanti' => 'sinop.edu.tr'],
            ['baslik' => 'Sivas Bilim ve Teknoloji Üniversitesi',   'il' => 58, 'mailUzanti' => 'sivas.edu.tr'],
            ['baslik' => 'Sivas Cumhuriyet Üniversitesi',           'il' => 58, 'mailUzanti' => 'cumhuriyet.edu.tr'],
            ['baslik' => 'Şırnak Üniversitesi',                     'il' => 73, 'mailUzanti' => 'sirnak.edu.tr'],
            ['baslik' => 'Tarsus Üniversitesi',                     'il' => 33, 'mailUzanti' => 'tarsus.edu.tr'],
            ['baslik' => 'Ted Üniversitesi (Vakıf)',                'il' => 6,  'mailUzanti' => 'tedu.edu.tr'],
            ['baslik' => 'Tekirdağ Namık Kemal Üniversitesi',       'il' => 59, 'mailUzanti' => 'nku.edu.tr'],
            ['baslik' => 'Tokat Gaziosmanpaşa Üniversitesi',        'il' => 60, 'mailUzanti' => 'gop.edu.tr'],
            ['baslik' => 'Trabzon Üniversitesi',                    'il' => 61, 'mailUzanti' => 'trabzon.edu.tr'],
            ['baslik' => 'Trakya Üniversitesi',                     'il' => 22, 'mailUzanti' => 'trakya.edu.tr'],
            ['baslik' => 'Türk Alman Üniversitesi',                 'il' => 34, 'mailUzanti' => 'tau.edu.tr'],
            ['baslik' => 'Ufuk Üniversitesi (Vakıf)',               'il' => 6,  'mailUzanti' => 'ufuk.edu.tr'],
            ['baslik' => 'Uşak Üniversitesi',                       'il' => 64, 'mailUzanti' => 'usak.edu.tr'],
            ['baslik' => 'Van Yüzüncü Yıl Üniversitesi',            'il' => 65, 'mailUzanti' => 'yyu.edu.tr'],
            ['baslik' => 'Yalova Üniversitesi',                     'il' => 77, 'mailUzanti' => 'yalova.edu.tr'],
            ['baslik' => 'Yaşar Üniversitesi (Vakıf)',              'il' => 35, 'mailUzanti' => 'yasar.edu.tr'],
            ['baslik' => 'Yıldız Teknik Üniversitesi',              'il' => 34, 'mailUzanti' => 'yildiz.edu.tr'],
            ['baslik' => 'Yozgat Bozok Üniversitesi',               'il' => 66, 'mailUzanti' => 'bozok.edu.tr'],
            ['baslik' => 'Zonguldak Bülent Ecevit Üniversitesi',    'il' => 67, 'mailUzanti' => 'beun.edu.tr']
        ];


        $faker = Faker::create("tr_TR");

        foreach ($universiteler as $uni) {
            Isletme::create([
                'isletme_turleri_id' => 1,
                'iller_id'           => $uni['il'],
                'referans_kodu'      => strtoupper(Str::random(8)),
                'referans'           => null,
                'baslik'             => $uni['baslik'],
                'adres'              => $faker->address,
                'mailUzanti'         => $uni['mailUzanti'],
                'logoUrl'            => 'https://placehold.co/128x128',
                'websiteUrl'         => $faker->url,
                'xUrl'               => 'x.com/' . $faker->userName,
                'instagramUrl'       => 'instagram.com/' . $faker->userName,
                'linkedinUrl'        => 'linkedin.com/' . $faker->userName,
                'digerUrl'           => $faker->url,
            ]);
        }

        $bizim = Isletme::find(143);

        $bizim->update([
            'logoUrl' => asset('image/_TNKU_LOGO_TR.jpg')
        ]);
    }
}
