<?php

namespace Database\Seeders;

use App\Models\Isletme;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class IsletmeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universiteler = [
            ['baslik' => 'Abant İzzet Baysal Üniversitesi', 'il' => 14],
            ['baslik' => 'Abdullah Gül Üniversitesi', 'il' => 38],
            ['baslik' => 'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi', 'il' => 1],
            ['baslik' => 'Adıyaman Üniversitesi', 'il' => 2],
            ['baslik' => 'Afyon Kocatepe Üniversitesi', 'il' => 3],
            ['baslik' => 'Afyonkarahisar Sağlık Bilimleri Üniversitesi', 'il' => 3],
            ['baslik' => 'Ağrı İbrahim Çeçen Üniversitesi', 'il' => 4],
            ['baslik' => 'Aksaray Üniversitesi', 'il' => 68],
            ['baslik' => 'Amasya Üniversitesi', 'il' => 5],
            ['baslik' => 'Ankara Hacı Bayram Veli Üniversitesi', 'il' => 6],
            ['baslik' => 'Ankara Müzik ve Güzel Sanatlar Üniversitesi', 'il' => 6],
            ['baslik' => 'Ankara Sosyal Bilimler Üniversitesi', 'il' => 6],
            ['baslik' => 'Ankara Üniversitesi', 'il' => 6],
            ['baslik' => 'Antalya Akev Üniversitesi (Vakıf)', 'il' => 7],
            ['baslik' => 'Antalya Bilim Üniversitesi (Vakıf)', 'il' => 7],
            ['baslik' => 'Ardahan Üniversitesi', 'il' => 75],
            ['baslik' => 'Artvin Çoruh Üniversitesi', 'il' => 8],
            ['baslik' => 'Atatürk Üniversitesi', 'il' => 25],
            ['baslik' => 'Bahçeşehir Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'Balıkesir Üniversitesi', 'il' => 10],
            ['baslik' => 'Bandırma Onyedi Eylül Üniversitesi', 'il' => 10],
            ['baslik' => 'Bartın Üniversitesi', 'il' => 74],
            ['baslik' => 'Batman Üniversitesi', 'il' => 72],
            ['baslik' => 'Bayburt Üniversitesi', 'il' => 69],
            ['baslik' => 'Beykent Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'Bezmialem Vakıf Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'Bilecik Şeyh Edebali Üniversitesi', 'il' => 11],
            ['baslik' => 'Bingöl Üniversitesi', 'il' => 12],
            ['baslik' => 'Bitlis Eren Üniversitesi', 'il' => 13],
            ['baslik' => 'Boğaziçi Üniversitesi', 'il' => 34],
            ['baslik' => 'Bolu Abant İzzet Baysal Üniversitesi', 'il' => 14],
            ['baslik' => 'Bursa Teknik Üniversitesi', 'il' => 16],
            ['baslik' => 'Bursa Uludağ Üniversitesi', 'il' => 16],
            ['baslik' => 'Çanakkale Onsekiz Mart Üniversitesi', 'il' => 17],
            ['baslik' => 'Çankırı Karatekin Üniversitesi', 'il' => 18],
            ['baslik' => 'Çukurova Üniversitesi', 'il' => 1],
            ['baslik' => 'Demiroğlu Bilim Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'Dicle Üniversitesi', 'il' => 21],
            ['baslik' => 'Dokuz Eylül Üniversitesi', 'il' => 35],
            ['baslik' => 'Düzce Üniversitesi', 'il' => 81],
            ['baslik' => 'Ege Üniversitesi', 'il' => 35],
            ['baslik' => 'Erciyes Üniversitesi', 'il' => 38],
            ['baslik' => 'Erzincan Binali Yıldırım Üniversitesi', 'il' => 24],
            ['baslik' => 'Erzurum Teknik Üniversitesi', 'il' => 25],
            ['baslik' => 'Eskişehir Osmangazi Üniversitesi', 'il' => 26],
            ['baslik' => 'Eskişehir Teknik Üniversitesi', 'il' => 26],
            ['baslik' => 'Fırat Üniversitesi', 'il' => 23],
            ['baslik' => 'Galatasaray Üniversitesi', 'il' => 34],
            ['baslik' => 'Gaziantep İslam Bilim ve Teknoloji Üniversitesi', 'il' => 27],
            ['baslik' => 'Gaziantep Üniversitesi', 'il' => 27],
            ['baslik' => 'Gaziosmanpaşa Üniversitesi (Tokat Gaziosmanpaşa)', 'il' => 60],
            ['baslik' => 'Gebze Teknik Üniversitesi', 'il' => 41],
            ['baslik' => 'Giresun Üniversitesi', 'il' => 28],
            ['baslik' => 'Gümüşhane Üniversitesi', 'il' => 29],
            ['baslik' => 'Hacettepe Üniversitesi', 'il' => 6],
            ['baslik' => 'Hakkari Üniversitesi', 'il' => 30],
            ['baslik' => 'Hatay Mustafa Kemal Üniversitesi', 'il' => 31],
            ['baslik' => 'Harran Üniversitesi', 'il' => 63],
            ['baslik' => 'Hitit Üniversitesi', 'il' => 19],
            ['baslik' => 'Iğdır Üniversitesi', 'il' => 76],
            ['baslik' => 'İbn Haldun Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İhsan Doğramacı Bilkent Üniversitesi (Vakıf)', 'il' => 6],
            ['baslik' => 'İnönü Üniversitesi', 'il' => 44],
            ['baslik' => 'İskenderun Teknik Üniversitesi', 'il' => 31],
            ['baslik' => 'İstanbul 29 Mayıs Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Arel Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Atlas Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Aydın Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Beykent Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Bilgi Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Esenyurt Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Galata Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Gedik Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Gelişim Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Kent Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Kültür Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Medeniyet Üniversitesi', 'il' => 34],
            ['baslik' => 'İstanbul Medipol Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Okan Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Rumeli Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Sabahattin Zaim Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Teknik Üniversitesi', 'il' => 34],
            ['baslik' => 'İstanbul Ticaret Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstanbul Üniversitesi', 'il' => 34],
            ['baslik' => 'İstanbul Yeni Yüzyıl Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İstinye Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'İzmir Bakırçay Üniversitesi', 'il' => 35],
            ['baslik' => 'İzmir Demokrasi Üniversitesi', 'il' => 35],
            ['baslik' => 'İzmir Ekonomi Üniversitesi (Vakıf)', 'il' => 35],
            ['baslik' => 'İzmir Katip Çelebi Üniversitesi', 'il' => 35],
            ['baslik' => 'İzmir Tınaztepe Üniversitesi (Vakıf)', 'il' => 35],
            ['baslik' => 'İzmir Yüksek Teknoloji Enstitüsü', 'il' => 35],
            ['baslik' => 'Kadir Has Üniversitesi (Vakıf)', 'il' => 34],
            ['baslik' => 'Kafkas Üniversitesi', 'il' => 36],
            ['baslik' => 'Kahramanmaraş İstiklal Üniversitesi', 'il' => 46],
            ['baslik' => 'Kahramanmaraş Sütçü İmam Üniversitesi', 'il' => 46],
            ['baslik' => 'Kapadokya Üniversitesi (Vakıf)', 'il' => 50],
            ['baslik' => 'Karabük Üniversitesi', 'il' => 78],
            ['baslik' => 'Karadeniz Teknik Üniversitesi', 'il' => 61],
            ['baslik' => 'Karamanoğlu Mehmetbey Üniversitesi', 'il' => 70],
            ['baslik' => 'Kastamonu Üniversitesi', 'il' => 37],
            ['baslik' => 'Kayseri Üniversitesi', 'il' => 38],
            ['baslik' => 'Kırıkkale Üniversitesi', 'il' => 71],
            ['baslik' => 'Kırklareli Üniversitesi', 'il' => 39],
            ['baslik' => 'Kilis 7 Aralık Üniversitesi', 'il' => 79],
            ['baslik' => 'Kocaeli Üniversitesi', 'il' => 41],
            ['baslik' => 'Konya Gıda ve Tarım Üniversitesi (Vakıf)', 'il' => 42],
            ['baslik' => 'Konya Teknik Üniversitesi', 'il' => 42],
            ['baslik' => 'Kütahya Dumlupınar Üniversitesi', 'il' => 43],
            ['baslik' => 'Kütahya Sağlık Bilimleri Üniversitesi', 'il' => 43],
            ['baslik' => 'Malatya Turgut Özal Üniversitesi', 'il' => 44],
            ['baslik' => 'Manisa Celal Bayar Üniversitesi', 'il' => 45],
            ['baslik' => 'Mardin Artuklu Üniversitesi', 'il' => 47],
            ['baslik' => 'Marmara Üniversitesi', 'il' => 34],
            ['baslik' => 'Mersin Üniversitesi', 'il' => 33],
            ['baslik' => 'Mimar Sinan Güzel Sanatlar Üniversitesi', 'il' => 34],
            ['baslik' => 'Muğla Sıtkı Koçman Üniversitesi', 'il' => 48],
            ['baslik' => 'Munzur Üniversitesi', 'il' => 62],
            ['baslik' => 'Mustafa Kemal Üniversitesi (Hatay Mustafa Kemal)', 'il' => 31],
            ['baslik' => 'Muş Alparslan Üniversitesi', 'il' => 49],
            ['baslik' => 'Nevşehir Hacı Bektaş Veli Üniversitesi', 'il' => 50],
            ['baslik' => 'Niğde Ömer Halisdemir Üniversitesi', 'il' => 51],
            ['baslik' => 'Nuh Naci Yazgan Üniversitesi (Vakıf)', 'il' => 38],
            ['baslik' => 'Ondokuz Mayıs Üniversitesi', 'il' => 55],
            ['baslik' => 'Ordu Üniversitesi', 'il' => 52],
            ['baslik' => 'Orta Doğu Teknik Üniversitesi', 'il' => 6],
            ['baslik' => 'Osmaniye Korkut Ata Üniversitesi', 'il' => 80],
            ['baslik' => 'Ostim Teknik Üniversitesi (Vakıf)', 'il' => 6],
            ['baslik' => 'Pamukkale Üniversitesi', 'il' => 20],
            ['baslik' => 'Recep Tayyip Erdoğan Üniversitesi', 'il' => 53],
            ['baslik' => 'Sağlık Bilimleri Üniversitesi', 'il' => 34],
            ['baslik' => 'Sakarya Uygulamalı Bilimler Üniversitesi', 'il' => 54],
            ['baslik' => 'Sakarya Üniversitesi', 'il' => 54],
            ['baslik' => 'Samsun Üniversitesi', 'il' => 55],
            ['baslik' => 'Selçuk Üniversitesi', 'il' => 42],
            ['baslik' => 'Siirt Üniversitesi', 'il' => 56],
            ['baslik' => 'Sinop Üniversitesi', 'il' => 57],
            ['baslik' => 'Sivas Bilim ve Teknoloji Üniversitesi', 'il' => 58],
            ['baslik' => 'Sivas Cumhuriyet Üniversitesi', 'il' => 58],
            ['baslik' => 'Şırnak Üniversitesi', 'il' => 73],
            ['baslik' => 'Tarsus Üniversitesi', 'il' => 33],
            ['baslik' => 'Ted Üniversitesi (Vakıf)', 'il' => 6],
            ['baslik' => 'Tekirdağ Namık Kemal Üniversitesi', 'il' => 59],
            ['baslik' => 'Tokat Gaziosmanpaşa Üniversitesi', 'il' => 60],
            ['baslik' => 'Trabzon Üniversitesi', 'il' => 61],
            ['baslik' => 'Trakya Üniversitesi', 'il' => 22],
            ['baslik' => 'Türk Alman Üniversitesi', 'il' => 34],
            ['baslik' => 'Ufuk Üniversitesi (Vakıf)', 'il' => 6],
            ['baslik' => 'Uşak Üniversitesi', 'il' => 64],
            ['baslik' => 'Van Yüzüncü Yıl Üniversitesi', 'il' => 65],
            ['baslik' => 'Yalova Üniversitesi', 'il' => 77],
            ['baslik' => 'Yaşar Üniversitesi (Vakıf)', 'il' => 35],
            ['baslik' => 'Yıldız Teknik Üniversitesi', 'il' => 34],
            ['baslik' => 'Yozgat Bozok Üniversitesi', 'il' => 66],
            ['baslik' => 'Zonguldak Bülent Ecevit Üniversitesi', 'il' => 67]
        ];

        $faker = Faker::create("tr_TR");

        foreach ($universiteler as $uni) {
            Isletme::create([
                'isletme_turleri_id' => 1,
                'iller_id'           => $uni['il'],
                'referans_kodu'      => strtoupper(Str::random(8)),
                'referans'           => null,
                'baslik'             => $uni['baslik'],
                'adres'              => $faker->address,
                'logoUrl'            => 'https://placehold.co/128x128',
                'websiteUrl'         => $faker->url,
                'xUrl'               => 'x.com/' . $faker->userName,
                'instagramUrl'       => 'instagram.com/' . $faker->userName,
                'linkedinUrl'        => 'linkedin.com/' . $faker->userName,
                'digerUrl'           => $faker->url,
            ]);
        }

        $bizim = Isletme::find(143);

        $bizim->update([
            'logoUrl' => asset('image/_TNKU_LOGO_TR.jpg')
        ]);
    }
}
