import edjsHTML from 'editorjs-html';

const edjsParser = edjsHTML();

const editorJsData = {"time":1735222172281,"blocks":[{"id":"dvvZTExf22","type":"paragraph","data":{"text":"<span style=\"color: #abb2bf;\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam corrupti quas doloremque itaque sapiente, consectetur corporis facilis magni non eveniet mollitia cupiditate culpa quo? Ea repellendus rerum alias assumenda blanditiis.<\/span><span style=\"color: #abb2bf;\">Debitis rerum tempore harum cum ipsa, magni repudiandae molestias et assumenda, maxime officiis, totam beatae? Recusandae aspernatur eveniet, alias tempora atque quia, id voluptates architecto error labore, similique aut praesentium.<\/span>Voluptatibus ullam fuga cum iste. Deserunt vel i<a href=\"http:\/\/www.google.com\">nventore<\/a> quasi sunt minus ducimus quisquam voluptas id iusto quos quam officiis ipsam placeat suscipit eligendi, temporibus culpa rerum molestiae numquam. Voluptate, quidem?<span style=\"color: #abb2bf;\">Quos accusantium quasi eos eaque sunt quibusdam numquam a reprehenderit deserunt dolor nisi at accusamus, illum harum eius aut! Tempore veniam minima vero, sed reprehenderit dolore iure? Soluta, incidunt eos.<\/span><span style=\"color: #abb2bf;\">Dolorum nemo beatae expedita rem natus, doloremque vel commodi ullam! Id quidem illum amet aliquam? Dolore, omnis culpa ut non accusamus unde beatae voluptatibus reiciendis explicabo totam quibusdam reprehenderit et.<\/span><span style=\"color: #abb2bf;\">Explicabo aliquid praesentium necessitatibus obcaecati non accusantium nam debitis deserunt quam sapiente facilis ullam, beatae hic. Nemo ipsum inventore aperiam suscipit minima nam sapiente beatae unde ut deserunt, numquam voluptatum.<\/span><span style=\"color: #abb2bf;\">Impedit ducimus quis nulla molestias suscipit perferendis pariatur. Molestiae officia quidem ullam quae consequuntur, vel, eius omnis quibusdam dolor similique perspiciatis eligendi optio cumque quo quam nostrum nisi nemo ex.<\/span><span style=\"color: #abb2bf;\">Veniam, enim. Possimus dolorem quia temporibus deleniti, iusto praesentium earum totam explicabo cum, quisquam, dicta ex. Porro sint omnis est quos quibusdam nam eaque harum, recusandae consequuntur tenetur cumque quae.<\/span><span style=\"color: #abb2bf;\">Corrupti voluptatem cumque natus sapiente incidunt velit obcaecati animi quo modi iste aspernatur cum eaque rerum aliquid quam, enim accusamus quas. Tenetur voluptatum, cum laboriosam architecto perferendis necessitatibus? Eligendi, nostrum!<\/span><span style=\"color: #abb2bf;\">Quos molestiae dolorem possimus quibusdam nihil quas corporis deleniti iste fuga consequuntur sunt animi obcaecati officiis ipsa, excepturi, laborum perferendis eos numquam quia. Inventore, sequi nisi. Temporibus laudantium tenetur neque!<\/span>"},"tunes":{"alignmentTune":{"alignment":"left"}}}],"version":"2.30.7"};

// 1) parse() metodu her block'u parse edip bir array döndürür
const htmlBlocks = edjsParser.parse(editorJsData);

// 2) Birleştirelim
const htmlOutput = htmlBlocks.join('');

// Artık `htmlOutput` saf HTML string olarak elinizde
document.getElementById('editorCikti').innerHTML = htmlOutput;
